version: '3.5'
services:
  api1: #Api 1
    image: api:v1.0
    hostname: api1
    depends_on:
      - db
    expose:
    - "80"
    ports:
    - "6000:80"    
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: #Api 2
    image: api:v1.0
    hostname: api2
    depends_on:
      - db
    expose:
    - "80"
    ports:
    - "6001:80"   
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2   
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de dados
   image: mongo:latest
   expose:
      - "27017"
   ports:
      - "27017:27017"
   volumes:
      - mongodb_data:/data/db
   deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

volumes:
  mongodb_data: